/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BaseBrit(props) {
  const { nodes, materials } = useGLTF('/models/environment_models/Base.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.base.geometry}
        material={materials.citybits_texture}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/models/environment_models/Base.glb')
