/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Island(props) {
  const { nodes, materials } = useGLTF('/models/environment_models/Floating Island.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[0.124, 0.306, -2.77]}
        scale={2.347}
      />
    </group>
  )
}

useGLTF.preload('/models/environment_models/Floating Island.glb')
