/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NewTree(props) {
  const { nodes, materials } = useGLTF('/models/environment_models/Trees.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[200.468, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_1_1.geometry}
          material={materials.NormalTree_Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_1_2.geometry}
          material={materials.NormalTree_Leaves}
        />
      </group>
      <group position={[205.39, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_2_1.geometry}
          material={materials.NormalTree_Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_2_2.geometry}
          material={materials.NormalTree_Leaves}
        />
      </group>
      <group position={[210.091, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_3_1.geometry}
          material={materials.NormalTree_Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_3_2.geometry}
          material={materials.NormalTree_Leaves}
        />
      </group>
      <group position={[216.945, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_4_1.geometry}
          material={materials.NormalTree_Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_4_2.geometry}
          material={materials.NormalTree_Leaves}
        />
      </group>
      <group position={[221.728, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_5_1.geometry}
          material={materials.NormalTree_Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NormalTree_5_2.geometry}
          material={materials.NormalTree_Leaves}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/environment_models/Trees.glb')
