/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BaskeballCourt(props) {
  const { nodes, materials } = useGLTF('/models/college_models/Basketball court.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.06}>
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh004.geometry}
          material={materials['Impact_Block:island_rock.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh004_1.geometry}
          material={materials['Canteen_Area:Impact_Block:blcok_white_island.001']}
        /> */}
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.06}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh005.geometry}
          material={materials['Canteen_Area:blue_spot.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh005_1.geometry}
          material={materials['lambert67.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/college_models/Basketball court.glb')
