/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Britain(props) {
  const { nodes, materials } = useGLTF('/models/college_models/Britain.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials.black_tree_part}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3.geometry}
          material={materials.Chair1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_4.geometry}
          material={materials.windows_rod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5.geometry}
          material={materials.stripe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_6.geometry}
          material={materials.aiStandardSurface7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_7.geometry}
          material={materials.marveel_brit}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_8.geometry}
          material={materials.marble}
        />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_9.geometry} material={materials.roof} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_10.geometry}
          material={materials.lambert15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_11.geometry}
          material={materials.lambert14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_12.geometry}
          material={materials.lambert16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_13.geometry}
          material={materials.windows_wood_plus}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_14.geometry}
          material={materials.main_body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_15.geometry}
          material={materials.windows_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_16.geometry}
          material={materials.windows_glass_plus}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_17.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_18.geometry}
          material={materials.Brit_sitting}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/college_models/Britain.glb')
