/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Canteen(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/college_models/Canteen.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="pCube16"
          position={[-0.029, 0.005, -0.005]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.012}>
          <group
            name="transform35"
            position={[2.487, 0.414, 0.464]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={84.521}
          />
        </group>
        <group
          name="group1"
          position={[7.351, 5.547, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.814, 1.57, 1.57]}>
          <group name="pCube1" position={[-14.979, 1.11, 1.151]} scale={[3.534, 9.432, 2.49]}>
            <mesh
              name="Mesh011"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011.geometry}
              material={materials.side_building}
            />
            <mesh
              name="Mesh011_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_1.geometry}
              material={materials.blue_buildijg_sde}
            />
            <mesh
              name="Mesh011_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh011_2.geometry}
              material={materials.lambert11}
            />
          </group>
          <mesh
            name="pCube10"
            castShadow
            receiveShadow
            geometry={nodes.pCube10.geometry}
            material={materials.table_and_chair}
            position={[-15.433, -4.07, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube17"
            castShadow
            receiveShadow
            geometry={nodes.pCube17.geometry}
            material={materials.table_and_chair}
            position={[-13.879, -6.128, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube18"
            castShadow
            receiveShadow
            geometry={nodes.pCube18.geometry}
            material={materials.table_and_chair}
            position={[-13.879, -5.099, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube19"
            castShadow
            receiveShadow
            geometry={nodes.pCube19.geometry}
            material={materials.table_and_chair}
            position={[-13.879, -4.07, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube2"
            castShadow
            receiveShadow
            geometry={nodes.pCube2.geometry}
            material={materials.white}
            position={[-12.693, 3.751, 2.056]}
            scale={[0.607, 2.447, 0.602]}
          />
          <mesh
            name="pCube20"
            castShadow
            receiveShadow
            geometry={nodes.pCube20.geometry}
            material={materials.table_and_chair}
            position={[-17.789, -1.287, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube21"
            castShadow
            receiveShadow
            geometry={nodes.pCube21.geometry}
            material={materials.table_and_chair}
            position={[-17.789, -3.136, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube22"
            castShadow
            receiveShadow
            geometry={nodes.pCube22.geometry}
            material={materials.table_and_chair}
            position={[-17.789, -4.985, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube23"
            castShadow
            receiveShadow
            geometry={nodes.pCube23.geometry}
            material={materials.table_and_chair}
            position={[-19.483, -3.136, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube24"
            castShadow
            receiveShadow
            geometry={nodes.pCube24.geometry}
            material={materials.table_and_chair}
            position={[-19.483, -1.287, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube25"
            castShadow
            receiveShadow
            geometry={nodes.pCube25.geometry}
            material={materials.table_and_chair}
            position={[-19.483, -4.985, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube26"
            castShadow
            receiveShadow
            geometry={nodes.pCube26.geometry}
            material={materials.table_and_chair}
            position={[-29.432, -4.985, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube27"
            castShadow
            receiveShadow
            geometry={nodes.pCube27.geometry}
            material={materials.table_and_chair}
            position={[-29.432, -3.136, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube28"
            castShadow
            receiveShadow
            geometry={nodes.pCube28.geometry}
            material={materials.table_and_chair}
            position={[-29.432, -1.287, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube29"
            castShadow
            receiveShadow
            geometry={nodes.pCube29.geometry}
            material={materials.table_and_chair}
            position={[-27.396, -1.287, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube30"
            castShadow
            receiveShadow
            geometry={nodes.pCube30.geometry}
            material={materials.table_and_chair}
            position={[-27.396, -3.136, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube31"
            castShadow
            receiveShadow
            geometry={nodes.pCube31.geometry}
            material={materials.table_and_chair}
            position={[-27.396, -4.985, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube74"
            castShadow
            receiveShadow
            geometry={nodes.pCube74.geometry}
            material={materials.table_and_chair}
            position={[-21.153, -1.287, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube75"
            castShadow
            receiveShadow
            geometry={nodes.pCube75.geometry}
            material={materials.table_and_chair}
            position={[-21.153, -3.136, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube76"
            castShadow
            receiveShadow
            geometry={nodes.pCube76.geometry}
            material={materials.table_and_chair}
            position={[-21.153, -4.985, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube77"
            castShadow
            receiveShadow
            geometry={nodes.pCube77.geometry}
            material={materials.table_and_chair}
            position={[-22.761, -1.287, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube78"
            castShadow
            receiveShadow
            geometry={nodes.pCube78.geometry}
            material={materials.table_and_chair}
            position={[-22.761, -3.136, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube79"
            castShadow
            receiveShadow
            geometry={nodes.pCube79.geometry}
            material={materials.table_and_chair}
            position={[-22.761, -4.985, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube8"
            castShadow
            receiveShadow
            geometry={nodes.pCube8.geometry}
            material={materials.table_and_chair}
            position={[-15.433, -6.128, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube80"
            castShadow
            receiveShadow
            geometry={nodes.pCube80.geometry}
            material={materials.table_and_chair}
            position={[-25.392, -4.985, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube81"
            castShadow
            receiveShadow
            geometry={nodes.pCube81.geometry}
            material={materials.table_and_chair}
            position={[-25.392, -3.136, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube82"
            castShadow
            receiveShadow
            geometry={nodes.pCube82.geometry}
            material={materials.table_and_chair}
            position={[-25.392, -1.287, -1.045]}
            rotation={[0, 0, Math.PI]}
            scale={1.361}
          />
          <mesh
            name="pCube85"
            castShadow
            receiveShadow
            geometry={nodes.pCube85.geometry}
            material={materials.table_and_chair}
            position={[-13.736, -9.681, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube86"
            castShadow
            receiveShadow
            geometry={nodes.pCube86.geometry}
            material={materials.table_and_chair}
            position={[-13.736, -8.652, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube87"
            castShadow
            receiveShadow
            geometry={nodes.pCube87.geometry}
            material={materials.table_and_chair}
            position={[-13.736, -7.623, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube88"
            castShadow
            receiveShadow
            geometry={nodes.pCube88.geometry}
            material={materials.table_and_chair}
            position={[-15.399, -9.681, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube89"
            castShadow
            receiveShadow
            geometry={nodes.pCube89.geometry}
            material={materials.table_and_chair}
            position={[-15.399, -8.652, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube9"
            castShadow
            receiveShadow
            geometry={nodes.pCube9.geometry}
            material={materials.table_and_chair}
            position={[-15.433, -5.099, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube90"
            castShadow
            receiveShadow
            geometry={nodes.pCube90.geometry}
            material={materials.table_and_chair}
            position={[-15.399, -7.623, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="pCube91"
            castShadow
            receiveShadow
            geometry={nodes.pCube91.geometry}
            material={materials.lambert29}
            position={[-13.213, 3.751, 1.259]}
            scale={[0.015, 2.447, 0.166]}
          />
          <mesh
            name="polySurface57"
            castShadow
            receiveShadow
            geometry={nodes.polySurface57.geometry}
            material={materials.wood}
            position={[-21.129, -6.316, -3.171]}
            scale={2.601}
          />
          <mesh
            name="polySurface58"
            castShadow
            receiveShadow
            geometry={nodes.polySurface58.geometry}
            material={materials.wood}
            position={[-18.919, -9.264, -2.556]}
            scale={[1.381, 3.721, 2.308]}
          />
          <mesh
            name="polySurface59"
            castShadow
            receiveShadow
            geometry={nodes.polySurface59.geometry}
            material={materials.wood}
            position={[-21.129, -12.642, -3.171]}
            scale={2.601}
          />
          <mesh
            name="polySurface60"
            castShadow
            receiveShadow
            geometry={nodes.polySurface60.geometry}
            material={materials.wood}
            position={[-18.319, -11.545, -2.556]}
            scale={[1.256, 2.308, 2.308]}
          />
          <mesh
            name="pPlane3"
            castShadow
            receiveShadow
            geometry={nodes.pPlane3.geometry}
            material={materials.lambert11}
            position={[-9.936, 0.13, -0.717]}
            scale={[5.417, 9.916, 3.49]}
          />
          <group
            name="pPlane4"
            position={[-6.78, -8.887, -1.694]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[6.974, 6.651, 3.49]}>
            <mesh
              name="Mesh010"
              castShadow
              receiveShadow
              geometry={nodes.Mesh010.geometry}
              material={materials.learning_jone_canteen}
            />
            <mesh
              name="Mesh010_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh010_1.geometry}
              material={materials.inside_wall}
            />
            <mesh
              name="Mesh010_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh010_2.geometry}
              material={materials.leaning_zone_back_wall}
            />
          </group>
        </group>
        <group
          name="group1001"
          position={[7.351, 5.547, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.814, 1.57, 1.57]}>
          <group
            name="pPlane4001"
            position={[-6.78, -8.887, -1.694]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[6.974, 6.651, 3.49]}>
            <mesh
              name="polySurface62"
              castShadow
              receiveShadow
              geometry={nodes.polySurface62.geometry}
              material={materials.learning_jone_canteen}
              position={[0, -1.065, 0]}
              scale={[1, 1.14, 1]}
            />
          </group>
        </group>
        <group
          name="pCube93"
          position={[-1.254, 3.345, 10.703]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.034, 0.01, 0.03]}>
          <group
            name="transform47"
            position={[36.691, -1070.287, 112.994]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[29.251, 33.78, 100]}
          />
        </group>
        <group
          name="pCube94"
          position={[-1.444, 7.821, 10.849]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.034, 0.01, 0.005]}>
          <group
            name="transform56"
            position={[42.231, -1084.926, 1637.723]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[29.251, 209.406, 100]}
          />
        </group>
        <group
          name="pCube95"
          position={[-5.142, 7.138, 10.703]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.044, 0.01, 0.05]}>
          <group
            name="transform54"
            position={[118.045, -1070.287, 142.262]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[22.959, 19.929, 100]}
          />
        </group>
        <group
          name="pCube96"
          position={[-5.161, 10.267, 10.703]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.045, 0.01, 0.012]}>
          <group
            name="transform58"
            position={[114.281, -1070.287, 828.669]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[22.142, 80.713, 100]}
          />
        </group>
        <group
          name="pCube101"
          position={[-5.294, 8.38, 11.834]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.034, 0.01, 0.03]}>
          <group
            name="transform60"
            position={[154.863, -1183.418, 283.077]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[29.251, 33.78, 100]}
          />
        </group>
        <group
          name="pCube112"
          position={[-5.555, 4.615, 11.769]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.034, 0.01, 0.03]}>
          <group
            name="transform43"
            position={[162.497, -1176.886, 155.904]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[29.251, 33.78, 100]}
          />
        </group>
        <group
          name="pCube131"
          position={[0.736, 0.206, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}>
          <group
            name="transform44"
            position={[-73.618, 0, 20.566]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group
          name="pCube132"
          position={[-0.745, 9.06, 5.621]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.034, 0.01, 0.03]}>
          <group
            name="transform53"
            position={[21.793, -562.116, 306.038]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[29.251, 33.78, 100]}
          />
        </group>
        <group
          name="pCube133"
          position={[-4.271, 9.52, 7.122]}
          rotation={[Math.PI / 2, 0.508, 0]}
          scale={[0.045, 0.006, 0.012]}>
          <group
            name="transform49"
            position={[-20.011, -1269.326, 839.048]}
            rotation={[-1.988, -0.294, -0.656]}
            scale={[43.795, 71.323, 178.224]}
          />
        </group>
        <group
          name="pCube134"
          position={[0.072, 3.617, -1.713]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.008}>
          <group
            name="transform42"
            position={[-8.898, 211.125, 445.887]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={123.266}
          />
        </group>
        <group
          name="pCube135"
          position={[-8.728, 4.152, 3.357]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.008}>
          <group
            name="transform41"
            position={[436.546, 1134.992, 539.88]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={130.039}
          />
        </group>
        <group
          name="pCube136"
          position={[-8.728, 4.152, -7.16]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.008}>
          <group
            name="transform40"
            position={[-931.116, 1134.992, 539.88]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={130.039}
          />
        </group>
        <group
          name="pCube141"
          position={[-0.095, 2.765, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}>
          <group
            name="transform57"
            position={[9.547, 0, 276.473]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group
          name="pCube142"
          position={[1.122, 6.282, 0.598]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.003, 0.003, 0.029]}>
          <group
            name="transform52"
            position={[-398.178, -209.3, 213.736]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[354.895, 34.021, 350.14]}
          />
        </group>
        <group
          name="pCube143"
          position={[-10.361, 0.453, -2.785]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.008, 0.01, 0.01]}>
          <group
            name="transform39"
            position={[-344.349, 989.611, 43.221]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[95.513, 95.513, 123.642]}
          />
        </group>
        <group
          name="pCube144"
          position={[2.323, 4.958, 2.1]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.034, 0.004, 0.007]}>
          <group
            name="transform59"
            position={[-67.952, -527.13, 757.893]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[29.251, 152.867, 250.985]}
          />
        </group>
        <group
          name="pCube145"
          position={[4.874, 4.683, -0.879]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.005, 0.001, 0.002]}>
          <group
            name="transform61"
            position={[-942.081, 1114.609, 2962.932]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[193.302, 632.659, 1268.716]}
          />
        </group>
        <group
          name="pCube146"
          position={[4.754, 4.801, -0.879]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.005, 0.001, 0.001]}>
          <group
            name="transform62"
            position={[-918.943, 1114.609, 6208.483]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[193.302, 1293.165, 1268.716]}
          />
        </group>
        <group
          name="pCube147"
          position={[4.634, 4.87, -0.879]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.005, 0.001, 0.001]}>
          <group
            name="transform63"
            position={[-895.804, 1114.609, 8059.825]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[193.302, 1655.038, 1268.716]}
          />
        </group>
        <group name="pCube149" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="polySurface64">
            <group name="polySurface76" position={[0, 0, -276.473]}>
              <group
                name="transform55"
                position={[0, 0, 276.473]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
            </group>
            <group name="transform46" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          </group>
          <group name="transform45" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface65" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform48" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group
          name="polySurface77"
          position={[-4.478, 3.445, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.007, 0.01, 0.008]}>
          <group
            name="transform50"
            position={[626.747, 0, 442.967]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[139.969, 128.586, 100]}
          />
        </group>
        <group
          name="polySurface78"
          position={[-4.266, 6.141, -0.038]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.008, 0.01, 0.008]}>
          <group
            name="transform51"
            position={[543.912, 3.805, 735.77]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[127.508, 119.822, 100]}
          />
        </group>
        <group
          name="pCube150"
          position={[0.346, -3.112, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}>
          <mesh
            name="Mesh050"
            castShadow
            receiveShadow
            geometry={nodes.Mesh050.geometry}
            material={materials['lambert1.001']}
          />
          <mesh
            name="Mesh050_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh050_1.geometry}
            material={materials.yellow_buildng}
          />
          <mesh
            name="Mesh050_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh050_2.geometry}
            material={materials.railing_yellow_builidng}
          />
          <mesh
            name="Mesh050_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh050_3.geometry}
            material={materials.yellow_builidng_wall}
          />
          <mesh
            name="Mesh050_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh050_4.geometry}
            material={materials.windows_fram}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/college_models/Canteen.glb')
