/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CoffeeStation(props) {
  const { nodes, materials } = useGLTF('/public/models/college_models/coffee station.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials.uk_block_main_color}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials.coffee_roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials.Table_and_chair}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3.geometry}
          material={materials.Coffee_staation_bar}
        />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_4.geometry} material={materials.wood} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5.geometry}
          material={materials.lambert36}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/public/models/college_models/coffee station.glb')
