/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Impact(props) {
  const { nodes, materials } = useGLTF('/public/models/college_models/Impact Block.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.666}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube100.geometry}
          material={materials.green_windows}
          position={[-0.752, 0.203, -9.543]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube101.geometry}
          material={materials.green_windows}
          position={[-0.752, 0.272, -7.571]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube102.geometry}
          material={materials.green_windows}
          position={[-0.752, 0.272, -6.164]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube103.geometry}
          material={materials.green_windows}
          position={[-0.752, 0.272, -4.532]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube104.geometry}
          material={materials.green_windows}
          position={[-0.752, 0.272, -2.761]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube105.geometry}
          material={materials.green_windows}
          position={[-0.752, 0.272, -1.281]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube106.geometry}
          material={materials.green_windows}
          position={[0.72, -0.985, -0.086]}
          rotation={[0, 0, -0.319]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube111.geometry}
          material={materials.red_out}
          position={[0, 0, 2.897]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube113.geometry}
          material={materials.green_windows}
          position={[-0.752, -0.432, -7.571]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.181, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube114.geometry}
          material={materials.green_windows}
          position={[-0.752, -0.432, -6.132]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.181, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube115.geometry}
          material={materials.green_windows}
          position={[-0.752, -0.432, -4.474]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.181, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube116.geometry}
          material={materials.green_windows}
          position={[-0.752, -0.432, -2.746]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.181, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube117.geometry}
          material={materials.green_windows}
          position={[-0.752, -0.432, -1.234]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.181, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube118.geometry}
          material={materials.green_windows}
          position={[-0.752, -0.432, 0.256]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.181, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube119.geometry}
          material={materials.green_windows}
          position={[-0.752, 0.272, 0.156]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube120.geometry}
          material={materials.green_windows}
          position={[1.16, -7.069, -9.765]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube122.geometry}
          material={materials.red_out}
          position={[1.265, -6.375, -9.036]}
          rotation={[3.134, Math.PI / 2, 0]}
          scale={[0.176, 2.034, 0.214]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube123.geometry}
          material={materials.green_windows}
          position={[1.16, -6.434, -9.765]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube124.geometry}
          material={materials.green_windows}
          position={[1.16, -5.749, -9.765]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube125.geometry}
          material={materials.green_windows}
          position={[1.16, -6.434, -8.393]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 0.609]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube126.geometry}
          material={materials.green_windows}
          position={[1.16, -7.069, -8.393]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 0.609]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube127.geometry}
          material={materials.green_windows}
          position={[1.16, -5.749, -8.393]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 0.609]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube128.geometry}
          material={materials.red_out}
          position={[1.265, -6.375, -7.873]}
          rotation={[3.134, Math.PI / 2, 0]}
          scale={[0.176, 2.034, 0.214]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube129.geometry}
          material={materials.green_windows}
          position={[1.16, -7.069, -7.183]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 0.609]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube130.geometry}
          material={materials.green_windows}
          position={[1.16, -6.434, -7.183]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 0.609]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube131.geometry}
          material={materials.green_windows}
          position={[1.16, -5.749, -7.183]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 0.609]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube132.geometry}
          material={materials.red_out}
          position={[1.265, -6.375, -6.554]}
          rotation={[3.134, Math.PI / 2, 0]}
          scale={[0.176, 2.034, 0.214]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube133.geometry}
          material={materials.green_windows}
          position={[1.16, -5.749, -5.725]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube134.geometry}
          material={materials.green_windows}
          position={[1.16, -6.434, -5.725]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube135.geometry}
          material={materials.green_windows}
          position={[1.16, -7.069, -5.725]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.406, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube136.geometry}
          material={materials.red_out}
          position={[1.265, -6.375, -4.997]}
          rotation={[3.134, Math.PI / 2, 0]}
          scale={[0.176, 2.034, 0.214]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube138.geometry}
          material={materials.green_windows}
          position={[1.291, -1.427, -4.919]}
          rotation={[0, 0, -1.469]}
          scale={[0.406, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube139.geometry}
          material={materials.green_windows}
          position={[1.291, -1.427, -6.479]}
          rotation={[0, 0, -1.469]}
          scale={[0.406, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube140.geometry}
          material={materials.green_windows}
          position={[1.378, -3.175, -8.325]}
          rotation={[0, 0, -1.517]}
          scale={[0.72, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube141.geometry}
          material={materials.green_windows}
          position={[1.378, -2.001, -8.325]}
          rotation={[0, 0, -1.517]}
          scale={[0.72, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube142.geometry}
          material={materials.green_windows}
          position={[1.378, -4.305, -8.325]}
          rotation={[0, 0, -1.517]}
          scale={[0.72, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube144.geometry}
          material={materials.green_windows}
          position={[0.61, -0.944, -6.592]}
          rotation={[0, 0, -0.186]}
          scale={[0.52, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube145.geometry}
          material={materials.green_windows}
          position={[-0.161, -0.934, -4.735]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube146.geometry}
          material={materials.green_windows}
          position={[0.61, -0.944, -4.735]}
          rotation={[0, 0, -0.186]}
          scale={[0.52, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube147.geometry}
          material={materials.green_windows}
          position={[-0.161, -0.934, -2.865]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube148.geometry}
          material={materials.green_windows}
          position={[0.61, -0.956, -2.865]}
          rotation={[0, 0, -0.123]}
          scale={[0.52, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube149.geometry}
          material={materials.green_windows}
          position={[0.277, -0.934, -1.336]}
          scale={[0.52, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube150.geometry}
          material={materials.red_out}
          position={[0, 0, 1.183]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube151.geometry}
          material={materials.red_out}
          position={[0, 0, 4.745]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube152.geometry}
          material={materials.windows_very_blue}
          position={[-4.227, -9.296, -6.73]}
          scale={1.146}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube156.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -9.955, -1.421]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube157.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -7.933, -1.421]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube158.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -5.92, -1.421]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube159.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -5.92, -4.383]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube160.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -7.933, -4.383]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube161.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -9.955, -4.383]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube162.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -5.92, 0.196]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube163.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -7.933, 0.196]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube164.geometry}
          material={materials.windows_very_blue}
          position={[-3.875, -9.955, 0.196]}
          scale={1.097}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube29.geometry}
          material={materials.green_windows}
          position={[-2.282, 1.264, -0.304]}
          rotation={[-Math.PI / 3, 0, -Math.PI / 2]}
          scale={[0.005, 3.159, 0.595]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube30.geometry}
          material={materials.red_out}
          position={[-2.261, 1.102, -8.469]}
          rotation={[-1.579, 0, -Math.PI / 2]}
          scale={[0.176, 3.033, 0.252]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube31.geometry}
          material={materials.red_out}
          position={[-2.829, 1.094, -6.767]}
          rotation={[-1.579, 0, -Math.PI / 2]}
          scale={[0.176, 1.61, 0.214]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube32.geometry}
          material={materials.red_out}
          position={[-3.005, 1.098, -5.218]}
          rotation={[-1.579, 0, -Math.PI / 2]}
          scale={[0.176, 1.106, 0.212]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube33.geometry}
          material={materials.green_windows}
          position={[-3.038, 0.971, -4.667]}
          scale={[0.899, 0.019, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube34.geometry}
          material={materials.windows_cover_white}
          position={[-1.602, 0.657, -4.765]}
          scale={[0.647, 0.017, 0.885]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube35.geometry}
          material={materials.green_windows}
          position={[0.296, -0.939, -8.213]}
          rotation={[0, 0, -0.034]}
          scale={[1, 0.004, 0.921]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube36.geometry}
          material={materials.green_windows}
          position={[-0.161, -0.934, -6.592]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube39.geometry}
          material={materials.green_windows}
          position={[-0.163, -0.934, -0.058]}
          scale={[0.52, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube40.geometry}
          material={materials.green_windows}
          position={[0.204, -5.302, -9.687]}
          scale={[0.728, 0.006, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube41.geometry}
          material={materials.green_windows}
          position={[-3.038, 0.876, -7.75]}
          scale={[1, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube42.geometry}
          material={materials.green_windows}
          position={[-1.837, 0.876, -7.75]}
          scale={[1, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube43.geometry}
          material={materials.green_windows}
          position={[-2.341, 0.876, -9.447]}
          scale={[2.33, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube47.geometry}
          material={materials.green_windows}
          position={[-3.038, 0.876, -6.136]}
          scale={[1, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube48.geometry}
          material={materials.green_windows}
          position={[-1.595, 0.876, -6.136]}
          scale={[1, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube49.geometry}
          material={materials.green_windows}
          position={[-2.232, 0.876, -3.466]}
          scale={[1, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube50.geometry}
          material={materials.green_windows}
          position={[-2.272, 0.878, -1.838]}
          scale={[1.266, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube51.geometry}
          material={materials.green_windows}
          position={[-1.142, 0.878, -1.838]}
          scale={[0.39, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube52.geometry}
          material={materials.green_windows}
          position={[-3.322, 0.878, -1.838]}
          scale={[0.39, 0.017, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube53.geometry}
          material={materials.green_windows}
          position={[-0.723, -4.104, -9.765]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.914, 0.004, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube98.geometry}
          material={materials.buidling_main_body}
          position={[0, 0, 1.134]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube99.geometry}
          material={materials.lambert9}
          position={[0, 0, -8.418]}
          scale={[1, 1, 0.111]}
        />
        <group position={[0.449, 0.061, 2.831]} scale={[0.887, 0.804, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh036.geometry}
            material={materials.buidling_main_body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh036_1.geometry}
            material={materials.gray_in_buidling}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh036_2.geometry}
            material={materials.building_lower_part}
          />
        </group>
        <group position={[0.335, -2.926, 0.628]} scale={[2.101, 4.025, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh058.geometry}
            material={materials.buidling_main_body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh058_1.geometry}
            material={materials.windows_cover_white}
          />
        </group>
        <group position={[0.335, -2.926, 0.628]} scale={[2.101, 4.025, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh003.geometry}
            material={materials.light_ray_top_buidlings}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh003_1.geometry}
            material={materials.buidling_main_body}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface126.geometry}
          material={materials.buidling_main_body}
          position={[-1.738, -1.549, 0.634]}
        />
        <group position={[-1.738, -1.549, 0.634]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh084.geometry}
            material={materials.light_ray_top_buidlings}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh084_1.geometry}
            material={materials.buidling_main_body}
          />
        </group>
        <group position={[0, 0.032, 1.134]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh051.geometry}
            material={materials.windows_very_blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_1.geometry}
            material={materials.windows_handle}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_2.geometry}
            material={materials.windows_cover_white}
          />
        </group>
        <group position={[-2.062, 0.032, 1.134]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh001.geometry}
            material={materials.windows_very_blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh001_1.geometry}
            material={materials.windows_handle}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh001_2.geometry}
            material={materials.windows_cover_white}
          />
        </group>
        <group position={[-0.003, 0.678, 1.134]} scale={[1, 1.18, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh079.geometry}
            material={materials.windows_handle}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh079_1.geometry}
            material={materials.windows_very_blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh079_2.geometry}
            material={materials.windows_cover_white}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface151.geometry}
          material={materials.buidling_main_body}
          position={[-6.019, -7.178, 2.028]}
          scale={[0.998, 1.945, 0.328]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface152.geometry}
          material={materials.buidling_main_body}
          position={[-1.053, -12.045, -5.146]}
          scale={[0.362, 0.488, 0.296]}
        />
        <group position={[-6.019, -7.178, -0.708]} scale={[0.998, 1.945, 0.328]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh022.geometry}
            material={materials.buidling_main_body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_1.geometry}
            material={materials.windows_cover_white}
          />
        </group>
        <group position={[-0.908, -9.75, -0.08]} scale={[14.35, 12.972, 23.698]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh006.geometry}
            material={materials.island_rock}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh006_1.geometry}
            material={materials.blcok_white_island}
          />
        </group>
        <group position={[-0.908, -2.663, -0.08]} scale={[14.35, 12.972, 23.698]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh039.geometry}
            material={materials.island_rock}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh039_1.geometry}
            material={materials.blcok_white_island}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/college_models/Impact Block.glb')
