/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ING_Tech(props) {
  const { nodes, materials } = useGLTF('/models/college_models/ING_tech.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[-8.209, 2.878, -7.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.965, 1.712, 1.712]}>
        <group position={[21.036, -25.046, 0.184]} scale={0.794}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh.geometry}
            material={materials['Canteen_Area:roof_ot_hubu']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials['Canteen_Area:hub_door_upper']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_2.geometry}
            material={materials['Canteen_Area:Hub_railing']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3.geometry}
            material={materials['Canteen_Area:lambert26']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_4.geometry}
            material={materials['Canteen_Area:lambert23']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_5.geometry}
            material={materials['Canteen_Area:Hubu_Building']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_6.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_7.geometry}
            material={materials['Canteen_Area:door_hub_liht']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/college_models/ING_tech.glb')
