/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function IT(props) {
  const { nodes, materials } = useGLTF('/models/college_models/IT.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.672, 0, -0.071]} rotation={[Math.PI / 2, 0, -0.055]} scale={0.244}>
      </group>
      <group position={[0.316, 0, 0.034]} rotation={[Math.PI / 2, 0, 0]} scale={0.244}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials.lambert55}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_2.geometry}
          material={materials.lambert48}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_3.geometry}
          material={materials.lambert49}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_4.geometry}
          material={materials.lambert53}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_5.geometry}
          material={materials.lambert54}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_6.geometry}
          material={materials['Britain_Block_wth_small_island:white_building_main']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_7.geometry}
          material={materials.lambert56}
        />
      </group>
      {/* <group position={[0.316, 0, 0.034]} rotation={[Math.PI / 2, 0, 0]} scale={0.244}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002.geometry}
          material={materials['Impact_Block:island_rock']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002_1.geometry}
          material={materials['Impact_Block:blcok_white_island']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002_2.geometry}
          material={materials['Canteen_Area:Impact_Block:blcok_white_island']}
        />
      </group> */}
    </group>
  )
}

useGLTF.preload('/models/college_models/IT.glb')
