/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Skill(props) {
  const { nodes, materials } = useGLTF('/models/college_models/Skill block.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[1.721, -0.288, 4.841]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.017, 0.025, 0.019]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials['Banner.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials['Main_Building.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials['lambert5.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3.geometry}
          material={materials['lambert6.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_4.geometry}
          material={materials['lambert3.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5.geometry}
          material={materials['lambert1.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_6.geometry}
          material={materials['window_glass.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_7.geometry}
          material={materials['aiStandardSurface1.002']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/college_models/Skill block.glb')
