/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Skill(props) {
  const { nodes, materials } = useGLTF('/models/college_models/Skill.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-6.88, -0.718, 2.915]} rotation={[Math.PI / 2, 0, 0]} scale={1.267}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials['Britain_Block_wth_small_island:Skill__Block:Main_Building']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials['Britain_Block_wth_small_island:Skill__Block:lambert3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3.geometry}
          material={materials['Britain_Block_wth_small_island:Skill__Block:window_glass']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_4.geometry}
          material={materials['Britain_Block_wth_small_island:Skill__Block:lambert5']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5.geometry}
          material={materials['Britain_Block_wth_small_island:Skill__Block:aiStandardSurface1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_6.geometry}
          material={materials['Britain_Block_wth_small_island:Skill__Block:lambert6']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_7.geometry}
          material={materials['Britain_Block_wth_small_island:Skill__Block:skill_roof']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_8.geometry}
          material={materials['Britain_Block_wth_small_island:Skill__Block:Banner']}
        />
      </group>
      <group
        position={[6.616, 0.72, -2.811]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.626, 0.695, 0.626]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials['Britain_Block_wth_small_island:Impact_Block:island_rock']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials['Britain_Block_wth_small_island:Impact_Block:blcok_white_island']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/college_models/Skill.glb')
