/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function StartingPoint(props) {
  const { nodes, materials } = useGLTF('/models/college_models/Starting Point.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[5.801, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={3.273}>
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials['Impact_Block:island_rock']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials['Impact_Block:blcok_white_island']}
        /> */}
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials['Canteen_Area:Impact_Block:blcok_white_island']}
        /> */}
      </group>
      <group position={[-5.836, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={3.273}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials.Black1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials.start_pont_window1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_2.geometry}
          material={materials.Starting_point1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_3.geometry}
          material={materials.start_block_brown1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/college_models/Starting Point.glb')
